### ISSUE TITLE
Chunk Loading not working unless in dimension

### ISSUE THREAD

**Issue by 792343** [TheCBProject/ChickenChunks#61] opened 2020-12-24 16:17 UTC
As the problem states chunk loaders aren't working properly unless I'm in the dimension. Try to keep a pump loaded in the nether and it won't work unless I'm in the Nether. Modpack is Valhesia 3, 1.16.4 solo world

**Comment by 792343** [comment] 2020-12-24 16:21
I should also mention that the pump is mekanism and I'm using ender tanks

**Comment by covers1624** [comment] 2020-12-24 22:49
Duplicate of: https://github.com/TheCBProject/ChickenChunks/issues/52

**Closed as completed by covers1624** 2020-12-24 22:49 UTC
