### ISSUE TITLE
Chunk loader doesn't work in my server 1.16.4

### ISSUE THREAD

**Issue by gabryjust04** [TheCBProject/ChickenChunks#65] opened 2021-01-10 12:53 UTC
Chunk loaders doesnt't work, i tried it on many block like sugar canes, furnace, immersive machines..

**Comment by gabryjust04** [comment] 2021-01-10 13:12
Work only when i'm on the server, when i quit chunk loader die

**Comment by covers1624** [comment] 2021-01-10 13:38
Duplicate of #52

**Closed as completed by covers1624** 2021-01-10 13:38 UTC
