### ISSUE TITLE
Does it work on a survival world?

### ISSUE THREAD

**Issue by Oliweea** [TheCBProject/ChickenChunks#60] opened 2020-12-04 01:10 UTC
Does the mod work on a world in survival mode, I tried to use it, and went to the nether but the chunks weren't loaded when I came back. The crops didn't grow and my farms didn't produce anything aswell? Do I need to open to LAN or host a server on my PC?

**Comment by covers1624** [comment] 2020-12-07 08:16
Duplicate of: https://github.com/TheCBProject/ChickenChunks/issues/52

**Closed as completed by covers1624** 2020-12-07 08:16 UTC
