### ISSUE TITLE
Nether star modification is not working

### ISSUE THREAD

**Issue by Namoku** [TheCBProject/ChickenChunks#59] opened 2020-12-03 12:15 UTC
Playing ATM6 1.3.3 (apotheosis 1.16.3-4.4.1) all seems to be working excepts the nether star modification, when you leave the zone they don't spawn until you arrive again. The chunks are forceloaded.

**Comment by covers1624** [comment] 2020-12-03 14:30
Duplicate of: https://github.com/TheCBProject/ChickenChunks/issues/52

**Closed as completed by covers1624** 2020-12-03 14:30 UTC
