### ISSUE TITLE
Chicken Chunks not running when offline on a server

### ISSUE THREAD

**Issue by Teslakoyal** [TheCBProject/ChickenChunks#66] opened 2021-01-23 03:27 UTC
Chicken Chunks isn't running when off line or when not in the same dimension as the chunk loader. I have tried changing to config options to see if that fixes anything, but even with player specific exceptions to allow offline running it does not. Although it was noticed on the server with several other mods I tried it on the server and single player with only the bare necessity mods to make sure it wasn't a mod interaction issue. The chunk loader works fine as long as your online and in the same dimension as the chuck loader.

MC: 1.6.4
Forge: 35.1.34
Code Chicken Lib 1.8+: CodeChickenLib-1.16.4-3.5.1.408-universal
Chicken Chunks 1.8+: ChickenChunks-1.16.4-2.7.0.85-universal

**Comment by xElementzx** [comment] 2021-01-23 03:37
Quick Question, what are you trying to load?

**Comment by Teslakoyal** [comment] 2021-01-23 05:13
My base, so machines and such, crop growth, ore processing in furnaces animal breeding

**Comment by xElementzx** [comment] 2021-01-23 05:27
Okay, so just so you're aware currently due to a bug:
https://github.com/TheCBProject/ChickenChunks/issues/52 
Random tick events such as crop growth do not work when offline.
try checking if the chunks are infact being loaded with a block such as a command block running a command you can see in console when you are not on the server.

**Comment by Teslakoyal** [comment] 2021-01-23 07:12
the command block worked when offline and while in a different dimension, should have considered that since the Mine colonists appeared to be still moving around, didn't look at issue 52 since it was titled for 1.15 but after reading through it I see that someone was able to reproduce it in 1.16 as well. Not sure if it helps, or if the mods load chunks the same way, but AzureDoom's chunk loaders work, just prefer Chicken Chunks 1 chunk loader as apposed to having to have 20 single blocks around. Thanks for taking the time to work though this with me.

**Comment by xElementzx** [comment] 2021-01-23 07:42
all good mate,

Closed - Duplicate of https://github.com/TheCBProject/ChickenChunks/issues/52

**Closed as completed by xElementzx** 2021-01-23 07:42 UTC
