### ISSUE TITLE
chunk loader not working 1.15.2

### ISSUE THREAD

**Issue by perecnicek** [TheCBProject/ChickenChunks#56] opened 2020-10-15 14:11 UTC
Hi we have custom modpack on our SERVER I tried command block with say hello and it doesnt worked chunk loader is not loading the chunks.
Forge version - forge-1.15.2-31.2.31
mod version - ChickenChunks-1.15.2-2.5.0.77-universal
Also i have set the chunk loader will work only when players is online( i was online and i placed the loader but like i said it no working)

**Comment by MazdakFarzone** [comment] 2020-10-21 14:03
I have the same issue running Valhelsia 2:
The server is running Valhelsia 2 version 2.2.10 :
- Minecraft version 1.15.2
- Chicken Chunks 1.8.+ (ChickenChunks-1.15.2-2.5.0.88-universal)

Its buildable and you can use the lasers, it just doesn't chunk load!

**Comment by mulhollandaf** [comment] 2020-10-22 16:13
I'm seeing the same thing. It doesn't seem my chunks are even staying loaded when I am on the server, in a different area.

**Comment by einraz** [comment] 2020-10-23 17:14
Having the same issue on Forge 1.15.2. Doesn't seem to keep chunks loaded if I teleport to another world or log off. Checked the settings and the default behavior is that it should keep chunks loaded when offline.

**Comment by Reidlos65** [comment] 2020-11-03 02:39
Mine doesnt seem to stay loaded if i go to End or nether atm but thats on single player

**Comment by covers1624** [comment] 2020-11-07 11:58
Duplicate of: https://github.com/TheCBProject/ChickenChunks/issues/52

**Closed as completed by covers1624** 2020-11-07 11:58 UTC
